apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: anonymous92/node-webserver
        resources:
          requests:
            memory: "80Mi"
            cpu: "50m"
          limits:
            memory: "120Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: image-cache
          mountPath: /shared
        env:
        - name: PORT
          value: "3000"
      volumes:
      - name: image-cache
        emptyDir: {}

