apiVersion: batch/v1
kind: CronJob
metadata:
  name: wiki-todo-cronjob
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wiki-todo
              image: anonymous92/wiki-todo-cron
              command: ["/bin/bash", "-c"]
              args: ["/usr/local/bin/wiki-todo-cronjob.sh"]
              env:
                - name: PGHOST
                  value: "postgres-service"
                - name: PGDATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-config
                      key: POSTGRES_DB
                - name: PGUSER
                  valueFrom:
                    configMapKeyRef:
                      name: postgres-config
                      key: POSTGRES_USER
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PASSWORD
          restartPolicy: OnFailure
