apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      labels:
        app: todo-broadcaster
    spec:
      containers:
      - name: todo-broadcaster
        image: anonymous92/todo-broadcaster
        ports:
        - containerPort: 3000
        env:
        - name: NATS_URL
          valueFrom:
            configMapKeyRef:
              name: broadcaster-config
              key: NATS_URL
                                 
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: broadcaster-secrets
              key: DISCORD_TOKEN 
                                   
        - name: DISCORD_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: broadcaster-secrets
              key: DISCORD_WEBHOOK_URL

        - name: DISCORD_CHANNEL_ID
          valueFrom:
            configMapKeyRef:
              name: broadcaster-config
              key: DISCORD_CHANNEL_ID
