apiVersion: v1
kind: Service
metadata:
  name: ping-pong-service
  namespace: applications
spec:
  type: LoadBalancer      
  selector:
    app: ping-pong
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

