apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ping-pong-hpa
  namespace: applications
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ping-pong
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
