apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dummysites.stable.dwk
spec:
  group: stable.dwk
  names:
    kind: DummySite
    listKind: DummySiteList
    plural: dummysites
    singular: dummysite
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                website_url:
                  type: string
                description:
                  type: string

