apiVersion: v1
kind: Service
metadata:
  name: log-reader-service
  labels:
    app: log-app
spec:
  selector:
    app: log-app
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: ClusterIP
