name: Build, Push, and Deploy

on:
  push:

env:
  FRONTEND_IMAGE: anonymous92/node-webserver
  BACKEND_IMAGE: anonymous92/todo-backend
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build frontend Docker image
        run: |
          docker build -f Dockerfile -t $FRONTEND_IMAGE:$BRANCH-$GITHUB_SHA .
          docker tag $FRONTEND_IMAGE:$BRANCH-$GITHUB_SHA $FRONTEND_IMAGE:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push frontend Docker image
        run: |
          docker push $FRONTEND_IMAGE:$BRANCH-$GITHUB_SHA
          docker push $FRONTEND_IMAGE:latest

      - name: Build backend Docker image
        run: |
          docker build -f Dockerfile.backend -t $BACKEND_IMAGE:$BRANCH-$GITHUB_SHA .
          docker tag $BACKEND_IMAGE:$BRANCH-$GITHUB_SHA $BACKEND_IMAGE:latest

      - name: Push backend Docker image
        run: |
          docker push $BACKEND_IMAGE:$BRANCH-$GITHUB_SHA
          docker push $BACKEND_IMAGE:latest

      - name: Install kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y kubectl

      - name: Set up kubeconfig for Kubernetes cluster
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Install Kustomize
        uses: imranismail/setup-kustomize@v2.1

      - name: Create or select the appropriate namespace
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            NAMESPACE="default"
          else
            NAMESPACE="${{ github.ref_name }}-env"
            kubectl create namespace $NAMESPACE || echo "Namespace $NAMESPACE already exists"
          fi

      - name: Deploy with Kustomize
        run: |
          kustomize edit set image frontend=$FRONTEND_IMAGE:$BRANCH-$GITHUB_SHA backend=$BACKEND_IMAGE:$BRANCH-$GITHUB_SHA
          kustomize build . | kubectl apply -n $NAMESPACE -f -
          kubectl rollout status deployment todo-app -n $NAMESPACE
          kubectl rollout status deployment todo-backend -n $NAMESPACE
