apiVersion: v1
kind: Secret
metadata:
  name: broadcaster-secrets
  namespace: default
type: Opaque
data:
  DISCORD_TOKEN: TVRJNE16QXlPRFV3TVRBME1URXlNelF6TVEuR1RLdnJWLnJSemZNRVMxUmYwZFM0U3EyYW15dTV4aDBiVVA3QnM0NUprbHp3      
  DISCORD_WEBHOOK_URL: aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvd2ViaG9va3MvMTI4Mjk4NDk4MDMyNjEyMTUxNC9Fc1dYQnE1UXNrTmF1SnY1a3l2MmZNYTNVVG5qNFVIM0NrcTZfWlR3cDZkMlVhOUtfZW5paGktYXh1S1praE1pemNCeg==    
