apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todo-backend-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-backend
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
