apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: logs-app-hpa
  namespace: applications
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: log-output
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
