apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - name: ping-pong
        image: anonymous92/pingpong-app
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          httpGet:
            path: /healthz
            port: 3000
        resources:
          requests:
            memory: "80Mi"
            cpu: "50m"
          limits:
            memory: "120Mi"
            cpu: "100m" 
        ports:
        - containerPort: 3000
        env:
        - name: PGUSER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: PGDATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: PGHOST
          value: "postgres-service"
