FROM ubuntu:latest

RUN apt-get update && apt-get install -y wget postgresql-client bash

COPY wiki-todo-cronjob.sh /usr/local/bin/wiki-todo-cronjob.sh
RUN chmod +x /usr/local/bin/wiki-todo-cronjob.sh

ENTRYPOINT ["/usr/local/bin/wiki-todo-cronjob.sh"]
