apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ping-pong
  namespace: applications
spec:
  template:
    spec:
      containers:
        - name: ping-pong
          image: anonymous92/pingpong-app
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PGHOST
              value: "postgres-service"
      resources:
        requests:
          memory: "80Mi"
          cpu: "50m"
        limits:
          memory: "120Mi"
          cpu: "100m"
